- name: Copying MongoDB repository
  ansible.builtin.template:
    src: mongodb/repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present 