- name: Copying MongoDB repository
  ansible.builtin.template:
    src: mongodb/repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present 

- name: Updating the MongoDB config to be public
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'   

- name: Starting MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true

- name: Download and extract frontend
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Injecting the Mondb schema
  community.mongodb.mongodb_shell:
    file: "/tmp/{{ COMPONENT }}-main/catalogue.js"
    idempotent: yes

- name: Injecting the Mondb schema
  community.mongodb.mongodb_shell:
    file: "/tmp/{{ COMPONENT }}-main/users.js"
    idempotent: yes