- name: Installing Maven on {{COMPONENT}}-{{ENV}} Server
  ansible.builtin.package:
    name: maven
    state: present  

- name: Creating App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user
