- name: Demo on using the varibales on playbook
  hosts: all 
  vars:
    URL: play.google.com
  tasks:
    - name: Printing the value of variable
      ansible.builtin.debug:
        msg: value of URL is {{ URL }}

    - name: Printing value of variable which is not decalred
      ansible.builtin.debug:
        msg: value of URL is {{ CARNAME }}