- name: Demo on using conditions  
  hosts: all 
  tasks:
    - name: Run this task only when the distribution is CentOS
      ansible.builtin.debug:
        msg: I am centos machine
      when: ansible_distribution == "CentOS"

    - name: Run this task only when the distribution is Debian
      ansible.builtin.debug:
        msg: I am Debian machine
      when: ansible_distribution == "Debian"