- name: Demo on using conditions  
  hosts: all 
  vars:
    action: true
    bar: xyz
  tasks:
    - name: Run this task only when the distribution is CentOS
      ansible.builtin.debug:
        msg: I am centos machine
      when: ansible_distribution == "CentOS"

    - name: Run this task only when the distribution is Debian
      ansible.builtin.debug:
        msg: I am Debian machine
      when: ansible_distribution == "Debian"

    - name: Run this action
      ansible.builtin.debug:
        msg: I am learning ansible and I will only print when action is true
      when: action

    - name: I will run only when the value of bar is not decalred
      ansible.builtin.debug:
        msg: bar is not decalred
      when: bar is undefined
      