# Demo on Privilege escalation

- name: Demo on privilege escalation
  hosts: all 
  become: yes                           # Privilege Escalation : Runs the whole playbook as a root user.
  tasks:
    - name: checking the user id
      ansible.builtin.shell: id
      register: OUT

    - name: Printing the user details
      ansible.builtin.debug:
        msg: "{{ OUT.stdout }}"