- name: copying a file from source to destination location
  hosts: all 
  tasks:
  - name: copying the systemd file
    ansible.builtin.copy:
      src: systemd.txt
      dest: /home/centos/systemd.txt