- name: Installing the Erlang package
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash


- name: Configuring {{COMPONENT}}-{{ENV}}
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: rabbitmq-serve
    state: present  

- name: Starting {{COMPONENT}}
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Configuring Node Name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}