- name: Installing the Erlang package
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash


- name: Configuring {{COMPONENT}}-{{ENV}}
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: rabbitmq-serve
    state: present  

- name: Starting {{COMPONENT}}
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Download and extract frontend
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Injecting the Mondb schema
  community.mongodb.mongodb_shell:
    file: "/tmp/{{ COMPONENT }}-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue
    - users

- name: Configuring Node Name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}