- name: Copying the systemd file of {{COMPONENT}}-{{ENV}} Server
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    
- name: Starting {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true
    daemon_reload: true

